export const WIKI_KNOWLEDGE: Record<string, string> = {
  'marie-curie': `Marie Curie (nascida Maria Salomea Skłodowska; Varsóvia, 7 de novembro de 1867 – Passy, 4 de julho de 1934) foi uma física e química polonesa naturalizada francesa, que conduziu pesquisas pioneiras sobre radioatividade. Ela foi a primeira mulher a ganhar o Prêmio Nobel, sendo também a primeira pessoa e a única mulher a ganhar o prêmio duas vezes, além de ser a única pessoa a ser premiada em dois campos científicos diferentes (Física e Química). Ela também foi a primeira mulher a se tornar professora na Universidade de Paris. Suas realizações incluem o desenvolvimento da teoria da radioatividade (um termo que ela cunhou), técnicas para isolar isótopos radioativos e a descoberta de dois elementos, o polônio e o rádio.`,
  
  'einstein': `Albert Einstein (Ulm, 14 de março de 1879 – Princeton, 18 de abril de 1955) foi um físico teórico alemão. Desenvolveu a teoria da relatividade geral, um dos pilares da física moderna ao lado da mecânica quântica. É mais conhecido por sua fórmula de equivalência massa-energia, E = mc², que foi chamada de "a equação mais famosa do mundo". Ele recebeu o Prêmio Nobel de Física de 1921 "por seus serviços à física teórica e, especialmente, por sua descoberta da lei do efeito fotoelétrico", um passo fundamental no desenvolvimento da teoria quântica.`,
  
  'ada-lovelace': `Augusta Ada King, Condessa de Lovelace (nascida Byron; Londres, 10 de dezembro de 1815 – Londres, 27 de novembro de 1852), foi uma matemática e escritora inglesa. Hoje é reconhecida principalmente por ter escrito o primeiro algoritmo para ser processado por uma máquina, a Máquina Analítica de Charles Babbage. Durante o período em que esteve envolvida com o projeto de Babbage, ela percebeu que a máquina seria capaz de manipular símbolos de acordo com regras e que o computador poderia fazer muito mais do que apenas cálculos numéricos.`,
  
  'isaac-newton': `Sir Isaac Newton (Woolsthorpe-by-Colsterworth, 25 de dezembro de 1642 – Londres, 20 de março de 1727) foi um matemático, físico, astrônomo, teólogo e autor inglês (descrito em seus dias como um "filósofo natural") que é amplamente reconhecido como um dos cientistas mais influentes de todos os tempos e uma figura chave na Revolução Científica. Seu livro "Philosophiæ Naturalis Principia Mathematica", publicado pela primeira vez em 1687, lançou as bases para a mecânica clássica. Newton também fez contribuições seminais para a óptica e compartilha o crédito com Gottfried Wilhelm Leibniz pelo desenvolvimento do cálculo infinitesimal.`,
  
  'rosalind-franklin': `Rosalind Elsie Franklin (Londres, 25 de julho de 1920 – Londres, 16 de abril de 1958) foi uma química britânica e cristalógrafa de raios-X cujo trabalho foi fundamental para a compreensão das estruturas moleculares do DNA (ácido desoxirribonucleico), RNA (ácido ribonucleico), vírus, carvão e grafite. Embora seus trabalhos sobre carvão e vírus tenham sido apreciados em sua vida, sua contribuição para a descoberta da estrutura do DNA foi amplamente reconhecida postumamente.`,
  
  'charles-darwin': `Charles Robert Darwin (Shrewsbury, 12 de fevereiro de 1809 – Downe, 19 de abril de 1882) foi um naturalista, geólogo e biólogo britânico, célebre por seus avanços sobre evolução nas ciências biológicas. Juntamente com Alfred Russel Wallace, estabeleceu a ideia de que todas as espécies de vida descendem de ancestrais comuns e propôs a teoria científica de que esse padrão de ramificação da evolução resultou de um processo que ele chamou de seleção natural.`,
  
  'katherine-johnson': `Katherine Johnson (nascida Coleman; White Sulphur Springs, 26 de agosto de 1918 – Newport News, 24 de fevereiro de 2020) foi uma matemática, física e cientista espacial norte-americana. Ela fez contribuições fundamentais para a aeronáutica e exploração espacial dos Estados Unidos, calculando a trajetória para o Projeto Mercury e o voo da Apollo 11 à Lua em 1969. Conhecida como um "computador humano" por sua tremenda capacidade matemática e por trabalhar na NASA com pouquíssimo reconhecimento inicial devido a segregação racial e de gênero.`,
  
  'galileo-galilei': `Galileu Galilei (Pisa, 15 de fevereiro de 1564 – Arcetri, 8 de janeiro de 1642) foi um astrônomo, físico e engenheiro florentino, às vezes descrito como polímata. Ele desempenhou um papel importante na revolução científica. Suas realizações incluem melhorias no telescópio e consequentes observações astronômicas e suporte ao copernicanismo. Galileu foi chamado de "pai da astronomia observacional moderna", "pai da física moderna", "pai da ciência moderna" e "pai da ciência moderna".`,
  
  'jane-goodall': `Dame Jane Morris Goodall (Londres, 3 de abril de 1934) é uma primatologista, etóloga e antropóloga britânica. É considerada a maior especialista do mundo em chimpanzés e é mais conhecida por seu estudo de 60 anos sobre as interações sociais e familiares de chimpanzés selvagens desde que foi pela primeira vez ao Parque Nacional de Gombe Stream, na Tanzânia, em 1960.`,
  
  'nikola-tesla': `Nikola Tesla (Smiljan, 10 de julho de 1856 – Nova Iorque, 7 de janeiro de 1943) foi um inventor, engenheiro elétrico e engenheiro mecânico sérvio-americano, mais conhecido por suas contribuições ao projeto do moderno sistema de fornecimento de eletricidade em corrente alternada (CA). Tesla obteve cerca de 300 patentes em todo o mundo por suas invenções.`,
  
  'socrates': `Sócrates (Alopece, c. 470 a.C. – Atenas, 399 a.C.) foi um filósofo ateniense do período clássico da Grécia Antiga. Creditado como um dos fundadores da filosofia ocidental, é até hoje uma figura enigmática, conhecida principalmente através dos relatos em obras de escritores que viveram mais tarde, especialmente dois de seus alunos, Platão e Xenofonte, e pelas peças de teatro de seu contemporâneo Aristófanes.`,
  
  'platao': `Platão (Atenas, 428/427 a.C. – Atenas, 348/347 a.C.) foi um filósofo e matemático do período clássico da Grécia Antiga, autor de diversos diálogos filosóficos e fundador da Academia em Atenas, a primeira instituição de educação superior do mundo ocidental. Juntamente com seu mentor, Sócrates, e seu pupilo, Aristóteles, Platão ajudou a construir os alicerces da filosofia natural, da ciência e da filosofia ocidental.`,
  
  'hannah-arendt': `Hannah Arendt (Linden, 14 de outubro de 1906 – Nova Iorque, 4 de dezembro de 1975) foi uma filósofa política alemã de origem judaica, uma das mais influentes do século XX. A privação de direitos e perseguição na Alemanha de Hitler, sua breve prisão e a emigração para os Estados Unidos marcaram sua obra, dedicada à análise do totalitarismo e à reabilitação da ação política como espaço de liberdade.`,
  
  'aristoteles': `Aristóteles (Estagira, 384 a.C. – Atenas, 322 a.C.) foi um filósofo e polímata da Grécia Antiga. Ao lado de Platão, de quem foi discípulo na Academia, foi um dos pensadores mais influentes da história da civilização ocidental. Aristóteles abordou quase todos os campos do conhecimento de sua época: biologia, física, metafísica, lógica, ética, política, retórica, poética, entre outros.`,
  
  'simone-de-beauvoir': `Simone Lucie Ernestine Marie Bertrand de Beauvoir (Paris, 9 de janeiro de 1908 – Paris, 14 de abril de 1986) foi uma escritora, intelectual, filósofa existencialista, ativista política, feminista e teórica social francesa. Embora não se considerasse uma filósofa, ela teve uma influência significativa no existencialismo feminista e na teoria feminista. Sua obra mais conhecida é "O Segundo Sexo" (1949), uma análise detalhada da opressão das mulheres e um tratado fundamental do feminismo contemporâneo.`,
  
  'confucio': `Confúcio (Qufu, 551 a.C. – Qufu, 479 a.C.) foi um pensador e filósofo chinês do Período das Primaveras e Outonos. A filosofia de Confúcio sublinhava uma moralidade pessoal e governamental, os procedimentos corretos nas relações sociais, a justiça e a sinceridade. Estes valores ganharam predominância na China em relação a outras doutrinas, como o legalismo e o taoísmo, durante a Dinastia Han.`,
  
  'hipatia': `Hipátia (Alexandria, c. 350–370 – Alexandria, 415) foi uma filósofa neoplatônica grega do Egito Romano. Foi a primeira mulher documentada como tendo sido matemática. Ensinou filosofia e astronomia na Escola Neoplatônica em Alexandria. Hipátia foi assassinada por uma multidão cristã, tornando-se um símbolo para o feminismo e para a oposição ao dogmatismo religioso.`,
  
  'descartes': `René Descartes (La Haye en Touraine, 31 de março de 1596 – Estocolmo, 11 de fevereiro de 1650) foi um filósofo, físico e matemático francês. É notabilizado sobretudo por seu trabalho revolucionário na filosofia e na ciência, mas também obteve reconhecimento matemático por sugerir a fusão da álgebra com a geometria - fato que gerou a geometria analítica e o sistema de coordenadas que hoje leva o seu nome. Sua frase mais famosa é "Penso, logo existo".`,
  
  'judith-butler': `Judith Pamela Butler (Cleveland, 24 de fevereiro de 1956) é uma filósofa pós-estruturalista estadunidense, que contribuiu para os campos do feminismo, teoria queer, filosofia política e ética. Ela é professora no Departamento de Literatura Comparada e no Programa de Teoria Crítica na Universidade da Califórnia em Berkeley. Sua obra mais famosa é "Problemas de Gênero: Feminismo e a Subversão da Identidade" (1990).`,
  
  'kant': `Immanuel Kant (Königsberg, 22 de abril de 1724 – Königsberg, 12 de fevereiro de 1804) foi um filósofo prussiano. Amplamente considerado como o principal filósofo da era moderna, Kant operou, na epistemologia, uma síntese entre o racionalismo continental e a tradição empírica inglesa. Sua obra principal, a "Crítica da Razão Pura" (1781), visa investigar os limites e a estrutura da razão humana.`,
  
  'cleytinho-do-grau': `Cleytinho do Grau é uma figura lendária do folclore urbano moderno, conhecido por sua habilidade inigualável de pilotar motocicletas utilizando apenas a roda traseira, manobra conhecida como "dar o grau". Além de suas proezas acrobáticas nas ruas, Cleytinho é um entusiasta da programação e da tecnologia, frequentemente debatendo algoritmos complexos enquanto equilibra sua moto. Ele representa a união improvável entre a cultura de rua e o mundo tech.`,
  
  'nelson-mandela': `Nelson Rolihlahla Mandela (Mvezo, 18 de julho de 1918 – Joanesburgo, 5 de dezembro de 2013) foi um advogado, líder rebelde e presidente da África do Sul de 1994 a 1999, considerado como o mais importante líder da África Negra, vencedor do Prêmio Nobel da Paz de 1993, e pai da moderna nação sul-africana, onde é normalmente referido como Madiba.`,
  
  'cleopatra': `Cleópatra VII Filopátor (Alexandria, 69 a.C. – Alexandria, 12 de agosto de 30 a.C.) foi a última governante ativa do Reino Ptolemaico do Egito. Como membro da dinastia ptolemaica, ela era descendente de seu fundador, Ptolemeu I Sóter, um general grego macedônio e companheiro de Alexandre, o Grande. Após sua morte, o Egito tornou-se uma província do Império Romano, marcando o fim do período helenístico.`,
  
  'lincoln': `Abraham Lincoln (Hodgenville, 12 de fevereiro de 1809 – Washington, D.C., 15 de abril de 1865) foi um político norte-americano que serviu como o 16.º presidente dos Estados Unidos, posto que ocupou de 4 de março de 1861 até seu assassinato em 1865. Lincoln liderou o país durante a sua maior crise interna, a Guerra Civil Americana, preservando a União e abolindo a escravidão.`,
  
  'elizabeth-i': `Elizabeth I (Greenwich, 7 de setembro de 1533 – Richmond, 24 de março de 1603) foi Rainha da Inglaterra e Irlanda de 1558 até sua morte. Filha de Henrique VIII e Ana Bolena, seu reinado ficou conhecido como a Era Elisabetana, um período de florescimento do drama inglês, liderado por dramaturgos como William Shakespeare e Christopher Marlowe, e pela destreza marítima de aventureiros como Francis Drake.`,
  
  'napoleao': `Napoleão Bonaparte (Ajaccio, 15 de agosto de 1769 – Santa Helena, 5 de maio de 1821) foi um líder militar e político francês que ganhou destaque durante a Revolução Francesa e liderou várias campanhas militares de sucesso durante as Guerras Revolucionárias. Como Napoleão I, foi Imperador dos Franceses de 1804 a 1814 e novamente brevemente em 1815 durante os Cem Dias.`,
  
  'angela-merkel': `Angela Dorothea Merkel (Hamburgo, 17 de julho de 1954) é uma política alemã que serviu como Chanceler da Alemanha de 2005 a 2021. Membro da União Democrata-Cristã (CDU), ela foi a primeira mulher a ocupar o cargo de chanceler na Alemanha. Merkel foi descrita como a líder de facto da União Europeia e a mulher mais poderosa do mundo durante grande parte de seu mandato.`,
  
  'julio-cesar': `Caio Júlio César (Roma, 12 de julho de 100 a.C. – Roma, 15 de março de 44 a.C.) foi um patrício, líder militar e político romano. Desempenhou um papel crítico na transformação da República Romana no Império Romano. Suas conquistas na Gália estenderam o domínio romano até o Oceano Atlântico. Foi assassinado por um grupo de senadores liderados por Brutus e Cássio.`,
  
  'golda-meir': `Golda Meir (Kiev, 3 de maio de 1898 – Jerusalém, 8 de dezembro de 1978) foi uma educadora, política e a quarta primeira-ministra de Israel. Foi a primeira mulher a liderar o Estado de Israel e a terceira mulher no mundo a ocupar tal posição. Conhecida como a "Dama de Ferro" da política israelense, liderou o país durante a Guerra do Yom Kippur.`,
  
  'gandhi': `Mohandas Karamchand Gandhi (Porbandar, 2 de outubro de 1869 – Nova Deli, 30 de janeiro de 1948) foi um advogado, nacionalista, anticolonialista e especialista em ética política indiano, que empregou resistência não violenta para liderar a campanha bem-sucedida para a independência da Índia do Reino Unido, e por sua vez inspirar movimentos pelos direitos civis e liberdade em todo o mundo.`,
  
  'thatcher': `Margaret Hilda Thatcher, Baronesa Thatcher (Grantham, 13 de outubro de 1925 – Londres, 8 de abril de 2013) foi uma política britânica que serviu como Primeira-Ministra do Reino Unido de 1979 a 1990 e Líder do Partido Conservador de 1975 a 1990. Foi a primeira mulher a ocupar o cargo e a pessoa que permaneceu mais tempo no cargo durante o século XX. Suas políticas ficaram conhecidas como Thatcherismo.`,
  
  'da-vinci': `Leonardo di Ser Piero da Vinci (Anchiano, 15 de abril de 1452 – Amboise, 2 de maio de 1519) foi um polímata nascido na atual Itália, uma das figuras mais importantes do Alto Renascimento, que se destacou como cientista, matemático, engenheiro, inventor, anatomista, pintor, escultor, arquiteto, botânico, poeta e músico. É frequentemente descrito como o arquétipo do homem do Renascimento.`,
  
  'frida-kahlo': `Magdalena Carmen Frida Kahlo y Calderón (Coyoacán, 6 de julho de 1907 – Coyoacán, 13 de julho de 1954) foi uma pintora mexicana conhecida por seus muitos retratos, autorretratos e obras inspiradas na natureza e nos artefatos do México. Inspirada pela cultura popular do país, ela empregou um estilo de arte folclórica ingênua para explorar questões de identidade, pós-colonialismo, gênero, classe e raça na sociedade mexicana.`,
  
  'shakespeare': `William Shakespeare (Stratford-upon-Avon, 23 de abril de 1564 – Stratford-upon-Avon, 23 de abril de 1616) foi um poeta, dramaturgo e ator inglês, tido como o maior escritor do idioma inglês e o mais influente dramaturgo do mundo. É chamado frequentemente de poeta nacional da Inglaterra e de "O Bardo de Avon". Suas obras remanescentes incluem cerca de 38 peças, 154 sonetos, dois longos poemas narrativos e alguns outros versos.`,
  
  'virginia-woolf': `Adeline Virginia Woolf (Londres, 25 de janeiro de 1882 – Lewes, 28 de março de 1941) foi uma escritora, ensaísta e editora britânica. Conhecida como uma das mais proeminentes figuras do modernismo literário do século XX. Entre suas obras mais famosas estão os romances "Mrs. Dalloway" (1925), "To the Lighthouse" (1927) e "Orlando" (1928), e o ensaio "A Room of One's Own" (1929).`,
  
  'michelangelo': `Michelangelo di Lodovico Buonarroti Simoni (Caprese, 6 de março de 1475 – Roma, 18 de fevereiro de 1564), conhecido simplesmente como Michelangelo, foi um escultor, pintor, arquiteto e poeta italiano do Alto Renascimento. Nascido na República de Florença, sua obra exerceu uma influência inigualável no desenvolvimento da arte ocidental. Suas obras mais famosas incluem os afrescos do teto da Capela Sistina e a estátua de David.`,
  
  'maya-angelou': `Maya Angelou (nascida Marguerite Annie Johnson; St. Louis, 4 de abril de 1928 – Winston-Salem, 28 de maio de 2014) foi uma escritora, poetisa e ativista dos direitos civis norte-americana. Publicou sete autobiografias, três livros de ensaios, vários livros de poesia e foi creditada em uma lista de peças, filmes e programas de televisão ao longo de mais de 50 anos.`,
  
  'picasso': `Pablo Ruiz y Picasso (Málaga, 25 de outubro de 1881 – Mougins, 8 de abril de 1973), foi um pintor espanhol, escultor, ceramista, cenógrafo, poeta e dramaturgo que passou a maior parte da sua vida adulta na França. Considerado um dos maiores e mais influentes artistas do século XX, é conhecido por co-fundar o movimento cubista, a invenção da escultura construída, a co-invenção da colagem e pela grande variedade de estilos que ajudou a desenvolver e explorar.`,
  
  'tarsila': `Tarsila de Aguiar do Amaral (Capivari, 1 de setembro de 1886 – São Paulo, 17 de janeiro de 1973) foi uma pintora, desenhista e tradutora brasileira e uma das figuras centrais da pintura e da primeira fase do movimento modernista no Brasil, ao lado de Anita Malfatti. Seu quadro "Abaporu", de 1928, inaugurou o movimento antropofágico nas artes plásticas.`,
  
  'bach': `Johann Sebastian Bach (Eisenach, 21 de março de 1685 – Leipzig, 28 de julho de 1750) foi um compositor, organista, cravista, violista e violinista alemão do período Barroco. É considerado um dos maiores compositores de todos os tempos. Suas obras são notáveis pela profundidade intelectual, domínio técnico e beleza artística.`,
  
  'toni-morrison': `Toni Morrison (nascida Chloe Anthony Wofford; Lorain, 18 de fevereiro de 1931 – Nova Iorque, 5 de agosto de 2019) foi uma escritora, editora e professora norte-americana. Seus romances são conhecidos por seus temas épicos, diálogos vívidos e personagens ricamente detalhados. Foi a primeira mulher negra a receber o Prêmio Nobel de Literatura, em 1993.`,
  
  'colombo': `Cristóvão Colombo (Gênova, 1451 – Valladolid, 20 de maio de 1506) foi um navegador e explorador italiano, responsável por liderar a frota que alcançou o continente americano em 12 de outubro de 1492, sob as ordens dos Reis Católicos de Espanha, no chamado descobrimento da América. Empreendeu a sua viagem através do Oceano Atlântico com o objetivo de atingir a Índia.`,
  
  'magalhaes': `Fernão de Magalhães (Sabrosa, c. 1480 – Mactan, 27 de abril de 1521) foi um navegador português que se notabilizou por ter organizado e comandado a primeira viagem de circum-navegação ao globo, ao serviço do rei de Espanha, Carlos I. Morreu em combate nas Filipinas antes de completar a viagem, que foi finalizada por Juan Sebastián Elcano.`,
  
  'vasco-da-gama': `Vasco da Gama (Sines, c. 1460/1469 – Cochim, 24 de dezembro de 1524) foi um navegador e explorador português. Na Era dos Descobrimentos, destacou-se por ter sido o comandante dos primeiros navios a navegar diretamente da Europa para a Índia, na mais longa viagem oceânica até então realizada, superior a uma volta completa ao mundo pelo Equador.`,
  
  'marco-polo': `Marco Polo (Veneza, 15 de setembro de 1254 – Veneza, 8 de janeiro de 1324) foi um mercador, embaixador e explorador veneziano cujas aventuras foram registradas no livro "As Viagens de Marco Polo", que descreveu para os europeus as maravilhas da China, de sua capital Pequim e de outras cidades e países da Ásia.`,
  
  'zheng-he': `Zheng He (Kunming, 1371 – 1433) foi um explorador, diplomata e almirante chinês durante a dinastia Ming. Liderou sete grandes expedições navais chinesas que cruzaram o Oceano Índico e chegaram ao Sudeste Asiático, Sul da Ásia, Oriente Médio e costa da África Oriental entre 1405 e 1433, demonstrando o poderio naval chinês.`,
  
  'ibn-battuta': `Abu Abdullah Muhammad Ibn Battuta (Tânger, 24 de fevereiro de 1304 – Marraquexe, 1368 ou 1369) foi um viajante e explorador berbere marroquino. É conhecido por seus extensos relatos de viagem, publicados no Rihla ("A Viagem"). Durante um período de trinta anos, Ibn Battuta visitou a maior parte do mundo islâmico e muitas terras não muçulmanas, incluindo a África do Norte, o Chifre da África, a África Ocidental, o Oriente Médio, a Ásia Central, o Sudeste Asiático, a Índia e a China.`,
  
  'sacagawea': `Sacagawea (c. 1788 – 20 de dezembro de 1812) foi uma mulher indígena da tribo Shoshone que acompanhou a expedição de Lewis e Clark em sua exploração do Oeste dos Estados Unidos. Viajando milhares de quilômetros de Dakota do Norte até o Oceano Pacífico entre 1804 e 1806, ela foi fundamental como guia e intérprete, além de ser um símbolo de paz para as tribos encontradas.`,
  
  'amundsen': `Roald Engelbregt Gravning Amundsen (Borge, 16 de julho de 1872 – Mar de Barents, c. 18 de junho de 1928) foi um explorador polar norueguês. Liderou a primeira expedição a atingir o Polo Sul em 14 de dezembro de 1911 e foi o primeiro a atravessar a Passagem do Noroeste. Também foi um dos primeiros a cruzar o Ártico pelo ar.`,
  
  'cook': `James Cook (Marton, 27 de outubro de 1728 – Kealakekua, 14 de fevereiro de 1779) foi um explorador, navegador e cartógrafo britânico. Capitão da Marinha Real Britânica, realizou três viagens ao Oceano Pacífico, mapeando muitas áreas e registrando várias ilhas e costas pela primeira vez em mapas europeus, incluindo a costa leste da Austrália e as ilhas do Havaí.`,
  
  'livingstone': `David Livingstone (Blantyre, 19 de março de 1813 – Chitambo, 1 de maio de 1873) foi um missionário médico escocês e explorador da África. Tornou-se um herói nacional vitoriano e sua fama como explorador foi reforçada por sua obsessão em descobrir as nascentes do rio Nilo. Seu encontro com Henry Morton Stanley deu origem à famosa frase: "Dr. Livingstone, suponho?".`,
  
  'muhammad-yunus': `Muhammad Yunus (Chittagong, 28 de junho de 1940) é um economista e banqueiro de Bangladesh. Foi o criador do Grameen Bank e ganhador do Prêmio Nobel da Paz em 2006 por seu trabalho no desenvolvimento do microcrédito e microfinanças, conceitos que ajudaram a tirar milhões de pessoas da pobreza ao fornecer pequenos empréstimos a empreendedores sem acesso a bancos tradicionais.`,
  
  'madam-cj-walker': `Madam C.J. Walker (nascida Sarah Breedlove; Delta, 23 de dezembro de 1867 – Irvington, 25 de maio de 1919) foi uma empreendedora, filantropa e ativista política e social norte-americana. Ela é registrada no Guinness Book of World Records como a primeira mulher a se tornar milionária por esforço próprio na América, fortuna construída através do desenvolvimento e marketing de uma linha de produtos de beleza e cabelo para mulheres negras.`,
  
  'ford': `Henry Ford (Springwells, 30 de julho de 1863 – Dearborn, 7 de abril de 1947) foi um empreendedor e engenheiro norte-americano, fundador da Ford Motor Company e o primeiro empresário a aplicar a montagem em série de forma a produzir automóveis em massa em menos tempo e a um menor custo. Sua introdução do Modelo T revolucionou o transporte e a indústria americana.`,
  
  'estee-lauder': `Estée Lauder (nascida Josephine Esther Mentzer; Nova Iorque, 1 de julho de 1906 – Nova Iorque, 24 de abril de 2004) foi uma empresária norte-americana. Ela co-fundou a Estée Lauder Companies, uma empresa pioneira de cosméticos. Lauder foi a única mulher na lista da revista Time de 1998 dos 20 gênios de negócios mais influentes do século XX.`,
  
  'walt-disney': `Walter Elias Disney (Chicago, 5 de dezembro de 1901 – Burbank, 15 de dezembro de 1966) foi um produtor cinematográfico, cineasta, diretor, roteirista, dublador, animador, empreendedor, filantropo e co-fundador da The Walt Disney Company. Pioneiro da indústria de animação americana, introduziu diversos desenvolvimentos na produção de desenhos animados. Como produtor de cinema, Disney detém o recorde de maior número de Oscars ganhos por um indivíduo.`,
  
  'oprah': `Oprah Gail Winfrey (Kosciusko, 29 de janeiro de 1954) é uma apresentadora de televisão, atriz, produtora, empresária e filantropa norte-americana. Vencedora de múltiplos prêmios Emmy, é mais conhecida por seu talk show The Oprah Winfrey Show, que foi o programa do gênero com maior audiência da história da televisão norte-americana.`,
  
  'jobs': `Steven Paul Jobs (São Francisco, 24 de fevereiro de 1955 – Palo Alto, 5 de outubro de 2011) foi um inventor, empresário e magnata americano no setor da informática. Notabilizou-se como co-fundador, presidente e diretor executivo da Apple Inc. e por revolucionar seis indústrias: computadores pessoais, filmes de animação, música, telefones, tablets e publicação digital.`,
  
  'musk': `Elon Reeve Musk (Pretória, 28 de junho de 1971) é um empreendedor e filantropo sul-africano-canadense, naturalizado norte-americano. É o fundador, CEO e engenheiro-chefe da SpaceX; CEO e arquiteto de produto da Tesla, Inc.; fundador da The Boring Company; e co-fundador da Neuralink e OpenAI.`,
  
  'bezos': `Jeffrey Preston Bezos (Albuquerque, 12 de janeiro de 1964) é um empresário, magnata da mídia e investidor norte-americano. É o fundador, presidente executivo e ex-CEO da Amazon, a maior empresa de comércio eletrônico e computação em nuvem do mundo.`,
  
  'ortega': `Amancio Ortega Gaona (Busdongo de Arbás, 28 de março de 1936) é um empresário espanhol, fundador e ex-presidente do grupo Inditex, proprietário de marcas como Zara, Massimo Dutti, Oysho, entre outras. É considerado um dos homens mais ricos do mundo e revolucionou a indústria da moda com o conceito de "fast fashion".`
};
